spring:
  cache:
    type: redis
    cache-names:
    - tasksByOwner
    redis:
      time-to-live: 2m
      cache-null-values: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USER}
      password: ${RABBITMQ_PASS}
  flyway:
    enabled: true
    validate-migration-naming: true
  datasource:
    url: ${DB_URL} 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
        - prometheus
  endpoint:
    health:
      show-details: when-authorized
      roles:
        - ADMIN

      probes:
        add-additional-paths: true
        enabled: true
