spring:
  flyway:
    enabled: true
    validate-migration-naming: true
  datasource:
    url: ${DB_URL} 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.flywaydb: DEBUG
